[libraries]
assertjCore = "org.assertj:assertj-core:3.27.6"
commons-io = "commons-io:commons-io:2.20.0"
commons-text = "org.apache.commons:commons-text:1.14.0"
dokkaPlugin = "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:2.1.0"
gradlePublishPlugin = "com.gradle.plugin-publish:com.gradle.plugin-publish.gradle.plugin:1.3.1"
junit4 = "junit:junit:4.13.2"
kotlinterPlugin = "org.jmailen.gradle:kotlinter-gradle:5.2.0"
nexusPublishPlugin = "io.github.gradle-nexus.publish-plugin:io.github.gradle-nexus.publish-plugin.gradle.plugin:2.0.0"
researchgateReleasePlugin = "net.researchgate.release:net.researchgate.release.gradle.plugin:3.1.0"
versionCatalogUpdatePlugin = "nl.littlerobots.version-catalog-update:nl.littlerobots.version-catalog-update.gradle.plugin:1.0.0"
vlciGradleExtensionsPlugin = "com.github.vlsi.gradle-extensions:com.github.vlsi.gradle-extensions.gradle.plugin:2.0.0"
